language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0snapshot
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

env:
  matrix:
    - ENABLE_OPCACHE=1
    - ENABLE_OPCACHE=0

before_install:
  - phpenv config-rm xdebug.ini || true

install:
    - phpize
    - ./configure
    - make
    - make install
    - composer install --no-interaction

before_script:
  - echo "extension=ds.so"                    >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "zend_extension=opcache.so"          >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "opcache.enable_cli=$ENABLE_OPCACHE" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer test
